from pathlib import Path
p=Path('/mnt/data/ff_22101_work/src/Admin/CampaignLocations.php')
s=p.read_text()
# version bumps
s=s.replace("Version: 2.2.101", "Version: 2.2.102")
s=s.replace("define('FIELDFLOW_VERSION', '2.2.101');", "define('FIELDFLOW_VERSION', '2.2.102');")
s=s.replace("$engineVersion = 'routing_intelligence_v9_geo_routing_brain';", "$engineVersion = 'routing_intelligence_v10_route_axis_lock';")
# add JS helpers in first editor after itemMacro
old="""    const itemZone=(it)=>normGeo(it.city||it.district||it.address||'');\n    const itemMacro=(it)=>normGeo(it.district||it.city||'');\n    const dayDominant=(day,fn)=>{ const m=new Map(); (day.items||[]).forEach(it=>{ const k=fn(it); if(k) m.set(k,(m.get(k)||0)+1); }); let best='', n=0; m.forEach((v,k)=>{ if(v>n){best=k;n=v;} }); return {key:best,count:n,map:m}; };\n"""
new="""    const itemZone=(it)=>normGeo(it.city||it.district||it.address||'');\n    const itemMacro=(it)=>normGeo(it.district||it.city||'');\n    const itemAxis=(it)=>{ const sp=startPoint(); if(!isFinite(Number(sp.lat))||!isFinite(Number(sp.lng))||!isFinite(Number(it.lat))||!isFinite(Number(it.lng))) return itemMacro(it); const dLat=Number(it.lat)-Number(sp.lat), dLng=Number(it.lng)-Number(sp.lng); const ns=Math.abs(dLat)<0.035?'eixo':(dLat>0?'norte':'sul'); const ew=Math.abs(dLng)<0.045?'eixo':(dLng>0?'interior':'litoral'); return ns+'|'+ew; };\n    const axisOpposition=(a,b)=>{ a=String(a||''); b=String(b||''); let p=0; if((a.includes('norte')&&b.includes('sul'))||(a.includes('sul')&&b.includes('norte'))) p+=1450; if((a.includes('interior')&&b.includes('litoral'))||(a.includes('litoral')&&b.includes('interior'))) p+=760; return p; };\n    const dayDominant=(day,fn)=>{ const m=new Map(); (day.items||[]).forEach(it=>{ const k=fn(it); if(k) m.set(k,(m.get(k)||0)+1); }); let best='', n=0; m.forEach((v,k)=>{ if(v>n){best=k;n=v;} }); return {key:best,count:n,map:m}; };\n"""
if old not in s: print('first helper anchor not found')
s=s.replace(old,new,1)
old="""      const z=itemZone(item), mz=itemMacro(item);\n      const dz=dayDominant(day,itemZone), dm=dayDominant(day,itemMacro);\n      if(z){ if(dz.map.has(z)) score-=650+Math.min(350,dz.map.get(z)*110); else if(dz.key&&dz.key!==z) score+=520+current.length*65; }\n      if(mz){ if(dm.map.has(mz)) score-=180; else if(dm.key&&dm.key!==mz) score+=300; }\n"""
new="""      const z=itemZone(item), mz=itemMacro(item), ax=itemAxis(item);\n      const dz=dayDominant(day,itemZone), dm=dayDominant(day,itemMacro), da=dayDominant(day,itemAxis);\n      if(z){ if(dz.map.has(z)) score-=650+Math.min(350,dz.map.get(z)*110); else if(dz.key&&dz.key!==z) score+=520+current.length*65; }\n      if(mz){ if(dm.map.has(mz)) score-=180; else if(dm.key&&dm.key!==mz) score+=300; }\n      if(ax){ if(da.map.has(ax)) score-=520+Math.min(420,da.map.get(ax)*140); else if(da.key&&da.key!==ax) score+=820+axisOpposition(da.key,ax)+(current.length*120); }\n"""
if old not in s: print('first geo block not found')
s=s.replace(old,new,1)
# second JS helpers
old="""  const itemZone2=(it)=>normGeo2(it.city||it.district||it.address||'');\n  const itemMacro2=(it)=>normGeo2(it.district||it.city||'');\n  function dayDominant2(day,fn){ const m=new Map(); (day.items||[]).forEach(it=>{ const k=fn(it); if(k) m.set(k,(m.get(k)||0)+1); }); let key='',count=0; m.forEach((v,k)=>{ if(v>count){key=k;count=v;} }); return {key,count,map:m}; }\n"""
new="""  const itemZone2=(it)=>normGeo2(it.city||it.district||it.address||'');\n  const itemMacro2=(it)=>normGeo2(it.district||it.city||'');\n  function itemAxis2(it){ const sp=startPoint(); if(!isFinite(Number(sp.lat))||!isFinite(Number(sp.lng))||!isFinite(Number(it.lat))||!isFinite(Number(it.lng))) return itemMacro2(it); const dLat=Number(it.lat)-Number(sp.lat), dLng=Number(it.lng)-Number(sp.lng); const ns=Math.abs(dLat)<0.035?'eixo':(dLat>0?'norte':'sul'); const ew=Math.abs(dLng)<0.045?'eixo':(dLng>0?'interior':'litoral'); return ns+'|'+ew; }\n  function axisOpposition2(a,b){ a=String(a||''); b=String(b||''); let p=0; if((a.includes('norte')&&b.includes('sul'))||(a.includes('sul')&&b.includes('norte'))) p+=1450; if((a.includes('interior')&&b.includes('litoral'))||(a.includes('litoral')&&b.includes('interior'))) p+=760; return p; }\n  function dayDominant2(day,fn){ const m=new Map(); (day.items||[]).forEach(it=>{ const k=fn(it); if(k) m.set(k,(m.get(k)||0)+1); }); let key='',count=0; m.forEach((v,k)=>{ if(v>count){key=k;count=v;} }); return {key,count,map:m}; }\n"""
if old not in s: print('second helper anchor not found')
s=s.replace(old,new,1)
old="""  function geoFitPenalty2(day,it){ const current=(day.items||[]); if(!current.length) return pointDistance(startPoint(), it)*1.4; let score=0; const z=itemZone2(it), mz=itemMacro2(it); const dz=dayDominant2(day,itemZone2), dm=dayDominant2(day,itemMacro2); if(z){ if(dz.map.has(z)) score-=650+Math.min(350,dz.map.get(z)*110); else if(dz.key&&dz.key!==z) score+=520+current.length*65; } if(mz){ if(dm.map.has(mz)) score-=180; else if(dm.key&&dm.key!==mz) score+=300; } let nearest=Number.MAX_SAFE_INTEGER; current.forEach(x=>{ nearest=Math.min(nearest, pointDistance(x,it)); }); if(isFinite(nearest)){ score+=Math.min(780, nearest*14); if(nearest<=6) score-=220; if(nearest>24) score+=Math.min(420,(nearest-24)*20); } return score; }\n"""
new="""  function geoFitPenalty2(day,it){ const current=(day.items||[]); if(!current.length) return pointDistance(startPoint(), it)*1.4; let score=0; const z=itemZone2(it), mz=itemMacro2(it), ax=itemAxis2(it); const dz=dayDominant2(day,itemZone2), dm=dayDominant2(day,itemMacro2), da=dayDominant2(day,itemAxis2); if(z){ if(dz.map.has(z)) score-=650+Math.min(350,dz.map.get(z)*110); else if(dz.key&&dz.key!==z) score+=520+current.length*65; } if(mz){ if(dm.map.has(mz)) score-=180; else if(dm.key&&dm.key!==mz) score+=300; } if(ax){ if(da.map.has(ax)) score-=520+Math.min(420,da.map.get(ax)*140); else if(da.key&&da.key!==ax) score+=820+axisOpposition2(da.key,ax)+(current.length*120); } let nearest=Number.MAX_SAFE_INTEGER; current.forEach(x=>{ nearest=Math.min(nearest, pointDistance(x,it)); }); if(isFinite(nearest)){ score+=Math.min(780, nearest*14); if(nearest<=6) score-=220; if(nearest>24) score+=Math.min(420,(nearest-24)*20); } return score; }\n"""
if old not in s: print('second geo function not found')
s=s.replace(old,new,1)
# PHP helpers before task_route_corridor_key
anchor="""    private static function task_route_corridor_key(array $task, array $startPoint = [], array $endPoint = []): string {\n"""
insert="""    private static function task_base_axis_key(array $task, array $startPoint = []): string {\n        if (!self::point_has_coordinates($task) || !self::point_has_coordinates($startPoint)) {\n            return self::task_macro_zone_key($task);\n        }\n\n        $dLat = (float)$task['lat'] - (float)$startPoint['lat'];\n        $dLng = (float)$task['lng'] - (float)$startPoint['lng'];\n        $northSouth = abs($dLat) < 0.035 ? 'eixo' : ($dLat > 0 ? 'norte' : 'sul');\n        $eastWest = abs($dLng) < 0.045 ? 'eixo' : ($dLng > 0 ? 'interior' : 'litoral');\n\n        $macro = self::task_macro_zone_key($task);\n        if (strpos($macro, 'interior') !== false) $eastWest = 'interior';\n        elseif (strpos($macro, 'litoral') !== false) $eastWest = 'litoral';\n\n        return trim('base|' . $northSouth . '|' . $eastWest);\n    }\n\n    private static function route_corridor_opposition_penalty(string $dominantKey, string $candidateKey): float {\n        $a = strtolower($dominantKey);\n        $b = strtolower($candidateKey);\n        $penalty = 0.0;\n        if ((strpos($a, 'norte') !== false && strpos($b, 'sul') !== false) || (strpos($a, 'sul') !== false && strpos($b, 'norte') !== false)) {\n            $penalty += 1450.0;\n        }\n        if ((strpos($a, 'interior') !== false && strpos($b, 'litoral') !== false) || (strpos($a, 'litoral') !== false && strpos($b, 'interior') !== false)) {\n            $penalty += 760.0;\n        }\n        return $penalty;\n    }\n\n"""
if anchor not in s: print('php anchor not found')
s=s.replace(anchor,insert+anchor,1)
# modify task_route_corridor_key start fallback and len2 fallback
s=s.replace("""        if (!self::point_has_coordinates($task)) return self::task_macro_zone_key($task);\n        $macro = self::task_macro_zone_key($task);\n        if (!self::point_has_coordinates($startPoint) || !self::point_has_coordinates($endPoint)) return $macro;\n""","""        if (!self::point_has_coordinates($task)) return self::task_macro_zone_key($task);\n        $macro = self::task_macro_zone_key($task);\n        if (!self::point_has_coordinates($startPoint)) return $macro;\n        if (!self::point_has_coordinates($endPoint)) return self::task_base_axis_key($task, $startPoint);\n""",1)
s=s.replace("""        if ($len2 <= 0.000001) return $macro;\n""","""        if ($len2 <= 0.000001) return self::task_base_axis_key($task, $startPoint);\n""",1)
# add PHP opposition in geoFitScore closure after corridor diff score
old="""            } elseif ($dominantCorridor !== '' && $dominantCorridor !== $taskCorridor) {\n                $score += 430.0;\n                $reasons[] = 'corredor diferente';\n            }\n"""
new="""            } elseif ($dominantCorridor !== '' && $dominantCorridor !== $taskCorridor) {\n                $score += 430.0 + self::route_corridor_opposition_penalty((string)$dominantCorridor, (string)$taskCorridor);\n                $reasons[] = 'corredor/eixo diferente';\n            }\n"""
if old not in s: print('php dayGeoFit corridor block not found')
s=s.replace(old,new,1)
# add opposition for load-first route strategy block(s)
s=s.replace("""                elseif ($dominantCorridor === $taskCorridor) $score -= 520.0;\n                else $score += 520.0;\n""","""                elseif ($dominantCorridor === $taskCorridor) $score -= 520.0;\n                else $score += 520.0 + self::route_corridor_opposition_penalty((string)$dominantCorridor, (string)$taskCorridor);\n""",1)
# docs/changelog
p.write_text(s)
