<?php
namespace RoutesPro\Admin;

use RoutesPro\Performance\Module;
use RoutesPro\Support\AdminPage;

if (!defined('ABSPATH')) exit;

class Performance {
    public static function render(): void {
        if (!Module::user_can_manage()) wp_die('Sem permissões.');
        Module::maybe_install();
        $tab = sanitize_key($_GET['tab'] ?? 'dashboard');
        $tabs = ['dashboard'=>'Growth Hub','academy'=>'Academy','media'=>'Biblioteca Media','missions'=>'Missões','certificates'=>'Certificados','automations'=>'Automações','reset'=>'Reset Engine','skills'=>'Skills','activity'=>'Activity Feed','shortcodes'=>'Shortcodes'];
        AdminPage::open('FieldFlow Growth Hub', 'Centro de formação, certificação, badges, missões e desenvolvimento das equipas de terreno.');
        echo '<style>.ffp-grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(220px,1fr));gap:16px}.ffp-card{background:#fff;border:1px solid #dbe3ef;border-radius:18px;padding:18px;box-shadow:0 10px 26px rgba(15,23,42,.06)}.ffp-kpi strong{display:block;font-size:34px;letter-spacing:-.04em}.ffp-tabs{display:flex;gap:8px;flex-wrap:wrap;margin:18px 0}.ffp-tabs a{padding:9px 13px;border-radius:999px;background:#fff;border:1px solid #dbe3ef;text-decoration:none}.ffp-tabs a.active{background:#0f172a;color:#fff;border-color:#0f172a}.ffp-form-grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(220px,1fr));gap:12px}.ffp-table{margin-top:16px}.ffp-pill{display:inline-block;border-radius:999px;padding:3px 8px;background:#eef2ff;color:#3730a3;font-size:12px}.ffp-muted{color:#64748b}.ffp-lesson-box{border:1px solid #e2e8f0;border-radius:16px;padding:12px;background:#f8fafc;margin:10px 0}.ffp-small{font-size:12px;color:#64748b}.ffp-actions{display:flex;gap:8px;flex-wrap:wrap}.ffp-actions a{font-size:12px}.ffp-danger{color:#b91c1c!important}.ffp-editing{border-color:#f59e0b!important;box-shadow:0 0 0 2px rgba(245,158,11,.12),0 10px 26px rgba(15,23,42,.06)!important}</style>';
        if ($tab === 'academy' || $tab === 'media' || $tab === 'missions') {
            echo <<<'HTML'
<style>
/* FieldFlow Growth Hub BO polish, conservative admin-only layer */
.ffp-card{box-sizing:border-box}.ffp-card h2{margin-top:0;font-size:20px;line-height:1.25}.ffp-card h3{margin:22px 0 8px;font-size:15px;text-transform:uppercase;letter-spacing:.04em;color:#334155}.ffp-card p{margin-top:8px;margin-bottom:12px}.ffp-card label{font-weight:600;color:#1e293b}.ffp-card input.regular-text,.ffp-card select,.ffp-card textarea{margin-top:6px;border-color:#cbd5e1;border-radius:8px}.ffp-card input.regular-text:focus,.ffp-card select:focus,.ffp-card textarea:focus{border-color:#0f172a;box-shadow:0 0 0 1px #0f172a}.ffp-form-grid{align-items:end}.ffp-lesson-box{position:relative;background:#fff;border-color:#d8e0ec;border-radius:14px;padding:14px 14px 10px;margin:12px 0}.ffp-lesson-box:before{content:'Learning Experience';display:block;margin:-2px 0 10px;font-size:11px;font-weight:800;letter-spacing:.08em;text-transform:uppercase;color:#64748b}.ffp-lesson-box .ffp-form-grid{grid-template-columns:80px minmax(260px,1.4fr) 150px minmax(260px,1.3fr) 100px 150px 170px;gap:10px}.ffp-lesson-box p{margin:0 0 10px}.ffp-lesson-box textarea{min-height:54px}.ffp-table table.widefat{border-radius:12px;overflow:hidden;border-color:#dbe3ef}.ffp-table table.widefat th{background:#f8fafc;color:#334155;font-weight:700}.ffp-table table.widefat td{vertical-align:middle}.ffp-actions{align-items:center}.ffp-actions a{display:inline-flex;align-items:center;padding:4px 8px;border-radius:999px;background:#f8fafc;border:1px solid #e2e8f0;text-decoration:none}.ffp-actions a:hover{background:#eef2ff;border-color:#c7d2fe}.ffp-actions a.ffp-danger{background:#fff7f7;border-color:#fecaca}.ffp-pill{font-weight:700}.ffp-editing{outline:2px solid rgba(245,158,11,.25)}.ffp-preview{background:#f8fafc;border:1px solid #dbe3ef;border-radius:18px;padding:18px;margin:12px 0}.ffp-preview-hero{background:linear-gradient(135deg,#0f172a,#1e293b);color:#fff;border-radius:18px;padding:22px}.ffp-preview-hero h2{color:#fff;margin:0 0 6px}.ffp-preview-list{margin:14px 0 0}.ffp-preview-item{background:#fff;border:1px solid #e2e8f0;border-radius:14px;padding:12px;margin:8px 0;display:flex;justify-content:space-between;gap:12px}.ffp-dup-box{background:#f8fafc;border:1px solid #e2e8f0;border-radius:14px;padding:12px;margin-top:12px}
@media(max-width:1280px){.ffp-lesson-box .ffp-form-grid{grid-template-columns:repeat(auto-fit,minmax(180px,1fr))}}
@media(max-width:782px){.ffp-tabs a{width:100%;text-align:center}.ffp-card{padding:14px}.ffp-lesson-box .ffp-form-grid{grid-template-columns:1fr}.ffp-card input.regular-text,.ffp-card select,.ffp-card textarea{width:100%}}
</style>
HTML;
        }

        echo '<div class="ffp-tabs">'; foreach($tabs as $key=>$label){$url=admin_url('admin.php?page=routespro-performance&tab='.$key); echo '<a class="'.esc_attr($tab===$key?'active':'').'" href="'.esc_url($url).'">'.esc_html($label).'</a>'; } echo '</div>';
        echo '<form method="post" action="'.esc_url(admin_url('admin-post.php')).'" style="margin:0 0 16px">'.wp_nonce_field('fieldflow_perf_seed_demo','_wpnonce',true,false).'<input type="hidden" name="action" value="fieldflow_perf_seed_demo"><button class="button button-primary">Criar demo Academy Enterprise</button> <span class="ffp-muted">Cria curso exemplo, media de apoio e missão prática no âmbito do primeiro cliente/campanha.</span></form>';
        if($tab==='academy') self::academy(); elseif($tab==='media') self::media(); elseif($tab==='missions') self::missions(); elseif($tab==='certificates') self::certificates(); elseif($tab==='automations') self::automations(); elseif($tab==='reset') self::reset_engine(); elseif($tab==='skills') self::skills(); elseif($tab==='activity') self::activity_feed_admin(); elseif($tab==='shortcodes') self::shortcodes(); else self::dashboard();
        AdminPage::close();
    }

    private static function dashboard(): void {
        $stats=Module::stats(); $top=Module::top_performers();
        echo '<div class="ffp-grid">'; self::kpi('Missões atribuídas',$stats['assigned'],'Volume operacional criado'); self::kpi('Taxa de conclusão',$stats['completion_rate'].'%','Execução das missões'); self::kpi('Skill Score',$stats['avg_score'],'Evolução das competências'); self::kpi('Cursos ativos',$stats['courses'],'Conteúdo de formação'); echo '</div>';
        echo '<div class="ffp-grid" style="margin-top:16px"><div class="ffp-card"><h2>Academy Enterprise 1.0</h2><p>Suporta conteúdos de formação em Canva, YouTube, PDF e links externos, mantendo o FieldFlow atual intacto.</p><ul><li>Cursos por cliente e campanha.</li><li>Lições multimédia com conclusão pelo operacional.</li><li>Missões ligadas a cursos.</li><li>Biblioteca Media reutilizável.</li></ul></div><div class="ffp-card"><h2>Top performers</h2>';
        if(!$top) echo '<p class="ffp-muted">Ainda sem dados do Growth Hub.</p>'; else { echo '<table class="widefat striped"><thead><tr><th>Utilizador</th><th>Concluídas</th><th>Score</th></tr></thead><tbody>'; foreach($top as $r){ echo '<tr><td>'.esc_html($r['display_name']).'</td><td>'.esc_html((string)$r['completed']).'</td><td>'.esc_html((string)round((float)$r['avg_score'])).'</td></tr>'; } echo '</tbody></table>'; }
        echo '</div></div>';
    }

    private static function kpi(string $label, $value, string $small): void { echo '<div class="ffp-card ffp-kpi"><span>'.esc_html($label).'</span><strong>'.esc_html((string)$value).'</strong><small class="ffp-muted">'.esc_html($small).'</small></div>'; }

    private static function academy(): void {
        $clients=Module::get_clients(); $projects=Module::get_projects(); $courses=Module::get_courses(['include_inactive'=>1]);
        $edit_id=absint($_GET['edit'] ?? 0); $edit=$edit_id ? Module::get_course($edit_id) : null; $lessons=$edit ? Module::get_lessons($edit_id) : [];
        echo '<div class="ffp-card '.($edit?'ffp-editing':'').'"><h2>'.($edit?'Editar curso Academy':'Novo curso Academy').'</h2><p class="ffp-muted">Academy UX Pro: cria experiências de aprendizagem ordenadas, obrigatórias ou opcionais, com tempo mínimo de consumo e estado de publicação.</p><form method="post" action="'.esc_url(admin_url('admin-post.php')).'">';
        wp_nonce_field('fieldflow_perf_save_course'); echo '<input type="hidden" name="action" value="fieldflow_perf_save_course"><input type="hidden" name="course_id" value="'.esc_attr((string)$edit_id).'">';
        echo '<div class="ffp-form-grid"><p><label>Cliente<br><select name="client_id"><option value="0">Global</option>'; foreach($clients as $c) echo '<option value="'.esc_attr($c['id']).'" '.selected((int)($edit['client_id']??0),(int)$c['id'],false).'>'.esc_html($c['name']).'</option>'; echo '</select></label></p>';
        echo '<p><label>Campanha<br><select name="project_id"><option value="0">Todas</option>'; foreach($projects as $p) echo '<option value="'.esc_attr($p['id']).'" '.selected((int)($edit['project_id']??0),(int)$p['id'],false).'>'.esc_html($p['name']).'</option>'; echo '</select></label></p>';
        echo '<p><label>Título<br><input class="regular-text" name="title" required value="'.esc_attr($edit['title']??'').'" placeholder="Retail Excellence Program"></label></p><p><label>Duração total min.<br><input type="number" name="duration_min" value="'.esc_attr((string)($edit['duration_min']??15)).'"></label></p><p><label>Pontos<br><input type="number" name="points" value="'.esc_attr((string)($edit['points']??100)).'"></label></p><p><label>Estado<br><select name="status"><option value="active" '.selected(($edit['status']??'active'),'active',false).'>Publicado</option><option value="draft" '.selected(($edit['status']??''),'draft',false).'>Rascunho</option><option value="archived" '.selected(($edit['status']??''),'archived',false).'>Arquivado</option></select></label></p></div>';
        echo '<p><label>Descrição<br><textarea name="description" rows="4" class="large-text" placeholder="Objetivo, aplicação no terreno e resultado esperado.">'.esc_textarea($edit['description']??'').'</textarea></label></p>';
        echo '<h3>Learning Experiences</h3><p class="ffp-muted">Define a ordem, se a lição conta para certificação e o tempo mínimo antes de permitir conclusão. Para conteúdo texto, podes deixar o URL vazio.</p>';
        if($edit && isset($_GET['preview'])) self::academy_preview($edit, $lessons);
        $rows=max(5,count($lessons)+1); for($i=0;$i<$rows;$i++){ $l=$lessons[$i]??[]; $idx=$i+1; echo '<div class="ffp-lesson-box">'; if(!empty($l['id'])){ $up=wp_nonce_url(admin_url('admin-post.php?action=fieldflow_perf_move_lesson&course_id='.$edit_id.'&lesson_id='.(int)$l['id'].'&dir=up'),'fieldflow_perf_move_lesson_'.(int)$l['id']); $down=wp_nonce_url(admin_url('admin-post.php?action=fieldflow_perf_move_lesson&course_id='.$edit_id.'&lesson_id='.(int)$l['id'].'&dir=down'),'fieldflow_perf_move_lesson_'.(int)$l['id']); echo '<div class="ffp-actions" style="justify-content:flex-end;margin-bottom:8px"><a href="'.esc_url($up).'">Subir</a><a href="'.esc_url($down).'">Descer</a></div>'; } echo '<div class="ffp-form-grid"><p><label>Ordem<br><input type="number" name="lesson_order[]" value="'.esc_attr((string)($l['sort_order']??$idx)).'" style="width:90px"></label></p><p><label>Título da lição<br><input class="regular-text" name="lesson_title[]" value="'.esc_attr($l['title']??'').'" placeholder="Ex: Argumentar valor sem desconto"></label></p><p><label>Tipo<br><select name="lesson_type[]">'; $types=['auto'=>'Automático','canva'=>'Canva','youtube'=>'YouTube','pdf'=>'PDF','link'=>'Link externo','text'=>'Texto rico']; foreach($types as $k=>$v) echo '<option value="'.esc_attr($k).'" '.selected(($l['content_type']??'auto'),$k,false).'>'.esc_html($v).'</option>'; echo '</select></label></p><p><label>URL<br><input class="regular-text" name="lesson_url[]" value="'.esc_attr($l['media_url']??'').'" placeholder="https://..."></label></p><p><label>Minutos<br><input type="number" name="lesson_min[]" value="'.esc_attr((string)($l['estimated_min']??3)).'" style="width:90px"></label></p><p><label>Tempo mínimo segundos<br><input type="number" name="lesson_min_watch[]" value="'.esc_attr((string)($l['min_watch_seconds']??8)).'" style="width:120px"></label></p><p><label><input type="hidden" name="lesson_required['.$i.']" value="0"><input type="checkbox" name="lesson_required['.$i.']" value="1" '.checked((int)($l['is_required']??1),1,false).'> Obrigatória para concluir</label></p></div><p><label>Notas da lição<br><textarea name="lesson_body[]" rows="2" class="large-text" placeholder="O que o operacional deve reter desta experiência.">'.esc_textarea($l['body']??'').'</textarea></label></p></div>'; }
        echo '<p><button class="button button-primary">'.($edit?'Guardar alterações':'Criar curso Academy').'</button> '.($edit?'<a class="button" href="'.esc_url(admin_url('admin.php?page=routespro-performance&tab=academy')).'">Cancelar edição</a> <a class="button" href="'.esc_url(admin_url('admin.php?page=routespro-performance&tab=academy&edit='.$edit_id.'&preview=1')).'">Pré-visualizar curso</a>':'').'</p></form></div>';
        echo '<div class="ffp-card"><h2>Duplicar curso para outra campanha</h2><p class="ffp-muted">Copia um curso completo, com lições e regras, para outro cliente/campanha. Fica em rascunho por segurança.</p><form method="post" action="'.esc_url(admin_url('admin-post.php')).'">'; wp_nonce_field('fieldflow_perf_duplicate_course_to_scope'); echo '<input type="hidden" name="action" value="fieldflow_perf_duplicate_course_to_scope"><div class="ffp-form-grid"><p><label>Curso origem<br><select name="course_id">'; foreach($courses as $dc) echo '<option value="'.esc_attr($dc['id']).'">#'.esc_html($dc['id']).' '.esc_html($dc['title']).'</option>'; echo '</select></label></p><p><label>Cliente destino<br><select name="target_client_id"><option value="0">Global</option>'; foreach($clients as $c) echo '<option value="'.esc_attr($c['id']).'">'.esc_html($c['name']).'</option>'; echo '</select></label></p><p><label>Campanha destino<br><select name="target_project_id"><option value="0">Todas</option>'; foreach($projects as $p) echo '<option value="'.esc_attr($p['id']).'">'.esc_html($p['name']).'</option>'; echo '</select></label></p><p><label>Estado destino<br><select name="target_status"><option value="draft">Rascunho</option><option value="active">Publicado</option></select></label></p></div><p><button class="button">Duplicar para campanha</button></p></form></div>';
        echo '<div class="ffp-card ffp-table"><h2>Cursos</h2><table class="widefat striped"><thead><tr><th>ID</th><th>Título</th><th>Âmbito</th><th>Lições</th><th>Pontos</th><th>Estado</th><th>Ações</th></tr></thead><tbody>';
        foreach($courses as $r){ $edit_url=admin_url('admin.php?page=routespro-performance&tab=academy&edit='.(int)$r['id']); $dup_url=wp_nonce_url(admin_url('admin-post.php?action=fieldflow_perf_duplicate_course&id='.(int)$r['id']),'fieldflow_perf_duplicate_course_'.(int)$r['id']); $del_url=wp_nonce_url(admin_url('admin-post.php?action=fieldflow_perf_delete_course&id='.(int)$r['id']),'fieldflow_perf_delete_course_'.(int)$r['id']); echo '<tr><td>#'.esc_html($r['id']).'</td><td><strong>'.esc_html($r['title']).'</strong><br><span class="ffp-muted">'.esc_html(wp_trim_words(wp_strip_all_tags($r['description']??''),14)).'</span></td><td>Cliente '.esc_html((string)($r['client_id']?:'Global')).'<br>Campanha '.esc_html((string)($r['project_id']?:'Todas')).'</td><td>'.esc_html((string)($r['lessons_count']??0)).'</td><td>'.esc_html($r['points']).'</td><td><span class="ffp-pill">'.esc_html($r['status']).'</span></td><td><span class="ffp-actions"><a href="'.esc_url($edit_url).'">Editar</a><a href="'.esc_url(admin_url('admin.php?page=routespro-performance&tab=academy&edit='.(int)$r['id'].'&preview=1')).'">Preview</a><a href="'.esc_url($dup_url).'">Duplicar</a><a class="ffp-danger" href="'.esc_url($del_url).'" onclick="return confirm(\'Apagar este curso? As lições e progresso associado serão removidos.\')">Apagar</a></span></td></tr>'; }
        if(!$courses) echo '<tr><td colspan="7">Ainda sem cursos.</td></tr>'; echo '</tbody></table></div>';
    }


    private static function academy_preview(array $course, array $lessons): void {
        echo '<div class="ffp-preview"><div class="ffp-preview-hero"><h2>'.esc_html($course['title'] ?? 'Curso').'</h2><p>'.esc_html(wp_trim_words(wp_strip_all_tags($course['description'] ?? ''), 32)).'</p><small>'.esc_html((string)($course['duration_min'] ?? 0)).' min · '.esc_html((string)($course['points'] ?? 0)).' pontos · '.esc_html($course['status'] ?? 'active').'</small></div>';
        echo '<div class="ffp-preview-list">';
        if(!$lessons){ echo '<p class="ffp-muted">Sem lições para pré-visualizar.</p>'; }
        foreach($lessons as $i=>$l){
            $type=strtoupper((string)($l['content_type'] ?? 'link'));
            $required=!empty($l['is_required']) ? 'Obrigatória' : 'Opcional';
            echo '<div class="ffp-preview-item"><div><strong>'.esc_html(($i+1).'. '.($l['title'] ?? 'Lição')).'</strong><br><span class="ffp-muted">'.esc_html(wp_trim_words(wp_strip_all_tags($l['body'] ?? ''), 18)).'</span></div><div style="text-align:right"><span class="ffp-pill">'.esc_html($type).'</span><br><small class="ffp-muted">'.esc_html($required).' · '.esc_html((string)($l['estimated_min'] ?? 0)).' min</small></div></div>';
        }
        echo '</div></div>';
    }

    private static function media(): void {
        $clients=Module::get_clients(); $projects=Module::get_projects(); $items=Module::get_media();
        $edit_id=absint($_GET['edit'] ?? 0); $edit=$edit_id ? Module::get_media_item($edit_id) : null;
        echo '<div class="ffp-card '.($edit?'ffp-editing':'').'"><h2>'.($edit?'Editar item de media':'Biblioteca Media').'</h2><p class="ffp-muted">Guarda links reutilizáveis de Canva, YouTube, PDF ou conteúdos externos por cliente e campanha.</p><form method="post" action="'.esc_url(admin_url('admin-post.php')).'">';
        wp_nonce_field('fieldflow_perf_save_media'); echo '<input type="hidden" name="action" value="fieldflow_perf_save_media"><input type="hidden" name="media_id" value="'.esc_attr((string)$edit_id).'">';
        echo '<div class="ffp-form-grid"><p><label>Cliente<br><select name="client_id"><option value="0">Global</option>'; foreach($clients as $c) echo '<option value="'.esc_attr($c['id']).'" '.selected((int)($edit['client_id']??0),(int)$c['id'],false).'>'.esc_html($c['name']).'</option>'; echo '</select></label></p>';
        echo '<p><label>Campanha<br><select name="project_id"><option value="0">Todas</option>'; foreach($projects as $p) echo '<option value="'.esc_attr($p['id']).'" '.selected((int)($edit['project_id']??0),(int)$p['id'],false).'>'.esc_html($p['name']).'</option>'; echo '</select></label></p>';
        echo '<p><label>Título<br><input class="regular-text" name="title" required value="'.esc_attr($edit['title']??'').'" placeholder="Apresentação produto"></label></p><p><label>Tipo<br><select name="media_type">'; $types=['auto'=>'Automático','canva'=>'Canva','youtube'=>'YouTube','pdf'=>'PDF','link'=>'Link externo']; foreach($types as $k=>$v) echo '<option value="'.esc_attr($k).'" '.selected(($edit['media_type']??'auto'),$k,false).'>'.esc_html($v).'</option>'; echo '</select></label></p><p><label>URL<br><input class="regular-text" name="media_url" required value="'.esc_attr($edit['media_url']??'').'" placeholder="https://..."></label></p><p><label>Estado<br><select name="status"><option value="active" '.selected(($edit['status']??'active'),'active',false).'>Ativo</option><option value="archived" '.selected(($edit['status']??''),'archived',false).'>Arquivado</option></select></label></p></div>';
        echo '<p><label>Notas<br><textarea name="notes" rows="3" class="large-text">'.esc_textarea($edit['notes']??'').'</textarea></label></p><p><button class="button button-primary">'.($edit?'Guardar alterações':'Guardar media').'</button> '.($edit?'<a class="button" href="'.esc_url(admin_url('admin.php?page=routespro-performance&tab=media')).'">Cancelar edição</a>':'').'</p></form></div>';
        echo '<div class="ffp-card ffp-table"><h2>Media guardada</h2><table class="widefat striped"><thead><tr><th>ID</th><th>Título</th><th>Tipo</th><th>Âmbito</th><th>URL</th><th>Ações</th></tr></thead><tbody>';
        foreach($items as $r){ $edit_url=admin_url('admin.php?page=routespro-performance&tab=media&edit='.(int)$r['id']); $del_url=wp_nonce_url(admin_url('admin-post.php?action=fieldflow_perf_delete_media&id='.(int)$r['id']),'fieldflow_perf_delete_media_'.(int)$r['id']); echo '<tr><td>#'.esc_html($r['id']).'</td><td><strong>'.esc_html($r['title']).'</strong><br><span class="ffp-muted">'.esc_html(wp_trim_words(wp_strip_all_tags($r['notes']??''),12)).'</span></td><td><span class="ffp-pill">'.esc_html($r['media_type']).'</span></td><td>Cliente '.esc_html((string)($r['client_id']?:'Global')).'<br>Campanha '.esc_html((string)($r['project_id']?:'Todas')).'</td><td><a href="'.esc_url($r['media_url']).'" target="_blank" rel="noopener">Abrir</a></td><td><span class="ffp-actions"><a href="'.esc_url($edit_url).'">Editar</a><a class="ffp-danger" href="'.esc_url($del_url).'" onclick="return confirm(\'Apagar este item da biblioteca?\')">Apagar</a></span></td></tr>'; }
        if(!$items) echo '<tr><td colspan="6">Ainda sem media.</td></tr>'; echo '</tbody></table></div>';
    }

    private static function missions(): void {
        $clients=Module::get_clients(); $projects=Module::get_projects(); $courses=Module::get_courses(); $users=Module::get_users_for_project(); $missions=Module::get_missions();
        $edit_id=absint($_GET['edit'] ?? 0); $edit=$edit_id ? Module::get_mission($edit_id) : null;
        echo '<div class="ffp-card '.($edit?'ffp-editing':'').'"><h2>'.($edit?'Editar missão operacional':'Nova missão operacional').'</h2><form method="post" action="'.esc_url(admin_url('admin-post.php')).'">'; wp_nonce_field('fieldflow_perf_save_mission'); echo '<input type="hidden" name="action" value="fieldflow_perf_save_mission"><input type="hidden" name="mission_id" value="'.esc_attr((string)$edit_id).'"><input type="hidden" name="replace_users" value="1">';
        echo '<div class="ffp-form-grid"><p><label>Cliente<br><select name="client_id"><option value="0">Global</option>'; foreach($clients as $c) echo '<option value="'.esc_attr($c['id']).'" '.selected((int)($edit['client_id']??0),(int)$c['id'],false).'>'.esc_html($c['name']).'</option>'; echo '</select></label></p>';
        echo '<p><label>Campanha<br><select name="project_id"><option value="0">Todas</option>'; foreach($projects as $p) echo '<option value="'.esc_attr($p['id']).'" '.selected((int)($edit['project_id']??0),(int)$p['id'],false).'>'.esc_html($p['name']).'</option>'; echo '</select></label></p>';
        echo '<p><label>Curso associado<br><select name="course_id"><option value="0">Sem curso</option>'; foreach($courses as $c) echo '<option value="'.esc_attr($c['id']).'" '.selected((int)($edit['course_id']??0),(int)$c['id'],false).'>'.esc_html($c['title']).'</option>'; echo '</select></label></p>';
        $due=!empty($edit['due_at']) ? date('Y-m-d\TH:i', strtotime($edit['due_at'])) : '';
        echo '<p><label>Título<br><input class="regular-text" name="title" required value="'.esc_attr($edit['title']??'').'" placeholder="Aplicar técnica de fecho alternativo"></label></p><p><label>Tipo<br><select name="mission_type">'; $types=['field_action'=>'Ação no terreno','training'=>'Formação','evidence'=>'Evidência','sales'=>'Comercial','correction'=>'Correção','checklist'=>'Checklist']; foreach($types as $k=>$v) echo '<option value="'.esc_attr($k).'" '.selected(($edit['mission_type']??'field_action'),$k,false).'>'.esc_html($v).'</option>'; echo '</select></label></p><p><label>Prioridade<br><select name="priority">'; $priorities=['low'=>'Baixa','normal'=>'Normal','high'=>'Alta','critical'=>'Crítica']; foreach($priorities as $k=>$v) echo '<option value="'.esc_attr($k).'" '.selected(($edit['priority']??'normal'),$k,false).'>'.esc_html($v).'</option>'; echo '</select></label></p><p><label>Tipo de evidência<br><select name="evidence_type">'; $evtypes=['link'=>'Link','photo'=>'Fotografia','video'=>'Vídeo','pdf'=>'PDF','note'=>'Nota escrita','mixed'=>'Mista']; foreach($evtypes as $k=>$v) echo '<option value="'.esc_attr($k).'" '.selected(($edit['evidence_type']??'link'),$k,false).'>'.esc_html($v).'</option>'; echo '</select></label></p><p><label>Meta<br><input type="number" name="target_value" value="'.esc_attr((string)($edit['target_value']??1)).'"></label></p><p><label>Pontos<br><input type="number" name="points" value="'.esc_attr((string)($edit['points']??100)).'"></label></p><p><label>Prazo<br><input type="datetime-local" name="due_at" value="'.esc_attr($due).'"></label></p><p><label>Estado<br><select name="status"><option value="active" '.selected(($edit['status']??'active'),'active',false).'>Ativa</option><option value="draft" '.selected(($edit['status']??''),'draft',false).'>Rascunho</option><option value="archived" '.selected(($edit['status']??''),'archived',false).'>Arquivada</option></select></label></p><p><label><input type="checkbox" name="evidence_required" value="1" '.checked((int)($edit['evidence_required']??0),1,false).'> Exigir evidência</label></p><p><label><input type="checkbox" name="approval_required" value="1" '.checked((int)($edit['approval_required']??0),1,false).'> Exigir aprovação BO</label></p></div>';
        echo '<div class="ffp-form-grid"><p><label>Descrição<br><textarea name="description" rows="4" class="large-text">'.esc_textarea($edit['description']??'').'</textarea></label></p><p><label>Critérios de sucesso<br><textarea name="success_criteria" rows="4" class="large-text" placeholder="Ex: contactar 3 clientes, registar objeção principal e anexar prova visual.">'.esc_textarea($edit['success_criteria']??'').'</textarea></label></p></div>';
        $quiz = $edit ? Module::parse_mission_quiz($edit) : [];
        echo '<div class="ffp-card" style="box-shadow:none;background:#f8fafc;margin:12px 0"><h3>Conteúdo e questionário da missão</h3><p class="ffp-muted">Opcional. Usa isto para mini-formações: vídeo/Canva/PDF/link seguido de um teste rápido antes de concluir a missão.</p><div class="ffp-form-grid"><p><label>Tipo de conteúdo<br><select name="mission_content_type">';
        $content_types=['none'=>'Sem conteúdo','youtube'=>'YouTube','canva'=>'Canva','pdf'=>'PDF','link'=>'Link externo','text'=>'Texto da descrição','quiz'=>'Quiz / Questionário']; foreach($content_types as $k=>$v) echo '<option value="'.esc_attr($k).'" '.selected(($edit['mission_content_type']??'none'),$k,false).'>'.esc_html($v).'</option>'; echo '</select></label></p><p><label>URL do conteúdo<br><input class="regular-text" name="mission_content_url" value="'.esc_attr($edit['mission_content_url']??'').'" placeholder="https://..."></label></p><p><label>Nota mínima %<br><input type="number" min="0" max="100" name="quiz_pass_score" value="'.esc_attr((string)($edit['quiz_pass_score']??70)).'"></label></p><p><label><input type="checkbox" name="quiz_enabled" value="1" '.checked((int)($edit['quiz_enabled']??0),1,false).'> Ativar questionário final</label></p></div>';
        echo '<div class="ffp-table ffp-mission-quiz-builder"><table class="widefat striped" id="ffpMissionQuizTable"><thead><tr><th>Pergunta</th><th>Tipo</th><th>Opções</th><th>Resposta/Pontos</th><th></th></tr></thead><tbody>';
        $rows = $quiz ?: [[]];
        foreach($rows as $qi=>$q){ self::mission_quiz_row((int)$qi, is_array($q)?$q:[]); }
        echo '</tbody></table><p><button type="button" class="button" id="ffpAddMissionQuestion">+ Adicionar questão</button> <span class="ffp-small">Podes criar perguntas de escolha múltipla, verdadeiro/falso, resposta curta ou longa, checklist, escala 1-5 e upload/evidência.</span></p></div><script>(function(){var table=document.getElementById("ffpMissionQuizTable");var btn=document.getElementById("ffpAddMissionQuestion");if(!table||!btn)return;function reindex(){table.querySelectorAll("tbody tr").forEach(function(row,i){var cb=row.querySelector("input[type=checkbox][name^=quiz_required]");if(cb){cb.name="quiz_required["+i+"]";}})}btn.addEventListener("click",function(){var tbody=table.querySelector("tbody");var tpl=table.querySelector("tbody tr").cloneNode(true);tpl.querySelectorAll("input,textarea,select").forEach(function(el){if(el.type==="checkbox"){el.checked=false}else{el.value=""} if(el.name==="quiz_type[]")el.value="multiple"; if(el.name==="quiz_points[]")el.value="1";});tbody.appendChild(tpl);reindex();});table.addEventListener("click",function(e){if(e.target&&e.target.classList.contains("ffp-remove-question")){var rows=table.querySelectorAll("tbody tr");if(rows.length>1){e.target.closest("tr").remove();reindex();}}});reindex();})();</script></div><p><label>Atribuir a utilizadores<br><select name="user_ids[]" multiple size="7" style="min-width:360px">'; foreach($users as $u){$id=is_object($u)?$u->ID:$u['ID'];$name=is_object($u)?$u->display_name:$u['display_name'];$email=is_object($u)?$u->user_email:$u['user_email']; echo '<option value="'.esc_attr($id).'">'.esc_html($name.' · '.$email).'</option>'; } echo '</select></label><br><span class="ffp-small">A validação final usa o scope do FieldFlow. Ao editar, as atribuições selecionadas substituem as anteriores.</span></p><p><button class="button button-primary">'.($edit?'Guardar alterações':'Criar missão').'</button> '.($edit?'<a class="button" href="'.esc_url(admin_url('admin.php?page=routespro-performance&tab=missions')).'">Cancelar edição</a>':'').'</p></form></div>';
        echo '<div class="ffp-card ffp-table"><h2>Missões</h2><table class="widefat striped"><thead><tr><th>ID</th><th>Missão</th><th>Curso</th><th>Prazo</th><th>Pontos</th><th>Estado</th><th>Ações</th></tr></thead><tbody>'; foreach($missions as $r){ $edit_url=admin_url('admin.php?page=routespro-performance&tab=missions&edit='.(int)$r['id']); $del_url=wp_nonce_url(admin_url('admin-post.php?action=fieldflow_perf_delete_mission&id='.(int)$r['id']),'fieldflow_perf_delete_mission_'.(int)$r['id']); echo '<tr><td>#'.esc_html($r['id']).'</td><td><strong>'.esc_html($r['title']).'</strong><br><span class="ffp-muted">'.esc_html(wp_trim_words(wp_strip_all_tags($r['description']??''),16)).'</span></td><td>'.esc_html($r['course_title']?:'').'</td><td>'.esc_html($r['due_at']?:'Sem prazo').'</td><td>'.esc_html($r['points']).'</td><td><span class="ffp-pill">'.esc_html($r['status']).'</span></td><td><span class="ffp-actions"><a href="'.esc_url($edit_url).'">Editar</a><a class="ffp-danger" href="'.esc_url($del_url).'" onclick="return confirm(\'Apagar esta missão e as atribuições associadas?\')">Apagar</a></span></td></tr>'; } if(!$missions) echo '<tr><td colspan="7">Ainda sem missões.</td></tr>'; echo '</tbody></table></div>';
    }


    private static function mission_quiz_row(int $qi, array $q=[]): void {
        $opts=!empty($q['options'])&&is_array($q['options'])?implode("\n",$q['options']):'';
        $type=(string)($q['type']??'multiple');
        $types=['multiple'=>'Escolha múltipla','truefalse'=>'Verdadeiro/Falso','short'=>'Resposta curta','long'=>'Resposta longa','checklist'=>'Checklist','scale'=>'Escala 1-5','evidence'=>'Upload/Evidência'];
        echo '<tr class="ffp-quiz-row"><td><input class="regular-text" name="quiz_question[]" value="'.esc_attr($q['question']??'').'" placeholder="Ex: Qual é o primeiro passo?"><br><label><input type="checkbox" name="quiz_required['.esc_attr((string)$qi).']" value="1" '.checked((int)($q['required']??1),1,false).'> Obrigatória</label></td><td><select name="quiz_type[]">';
        foreach($types as $k=>$v) echo '<option value="'.esc_attr($k).'" '.selected($type,$k,false).'>'.esc_html($v).'</option>';
        echo '</select><p class="ffp-small">Checklist usa opções por linha. Escala cria 1 a 5.</p></td><td><textarea name="quiz_options[]" rows="4" placeholder="Uma opção por linha">'.esc_textarea($opts).'</textarea></td><td><input class="regular-text" name="quiz_answer[]" value="'.esc_attr($q['answer']??'').'" placeholder="Resposta certa ou itens esperados"><br><label>Pontos <input type="number" min="1" max="100" name="quiz_points[]" value="'.esc_attr((string)($q['points']??1)).'" style="width:80px"></label><br><input class="regular-text" name="quiz_feedback[]" value="'.esc_attr($q['feedback']??'').'" placeholder="Feedback opcional"></td><td><button type="button" class="button ffp-remove-question">Remover</button></td></tr>';
    }


    private static function certificates(): void {
        global $wpdb;
        $clients=Module::get_clients(); $projects=Module::get_projects();
        $settings_table=Module::table('certificate_settings');
        $edit_id=absint($_GET['edit'] ?? 0);
        $edit=$edit_id ? $wpdb->get_row($wpdb->prepare("SELECT * FROM {$settings_table} WHERE id=%d",$edit_id),ARRAY_A) : null;
        if(!$edit) $edit=Module::get_certificate_settings();
        echo '<div class="ffp-card"><h2>Certificate Builder</h2><p class="ffp-muted">Configura certificados premium por cliente ou campanha. O PDF é emitido automaticamente quando o operacional conclui todas as lições do curso.</p><form method="post" action="'.esc_url(admin_url('admin-post.php')).'">';
        wp_nonce_field('fieldflow_perf_save_certificate_settings');
        echo '<input type="hidden" name="action" value="fieldflow_perf_save_certificate_settings"><input type="hidden" name="settings_id" value="'.esc_attr((string)$edit_id).'">';
        echo '<div class="ffp-form-grid"><p><label>Cliente<br><select name="client_id"><option value="0">Global</option>'; foreach($clients as $c) echo '<option value="'.esc_attr($c['id']).'" '.selected((int)($edit['client_id']??0),(int)$c['id'],false).'>'.esc_html($c['name']).'</option>'; echo '</select></label></p>';
        echo '<p><label>Campanha<br><select name="project_id"><option value="0">Todas</option>'; foreach($projects as $p) echo '<option value="'.esc_attr($p['id']).'" '.selected((int)($edit['project_id']??0),(int)$p['id'],false).'>'.esc_html($p['name']).'</option>'; echo '</select></label></p>';
        echo '<p><label>Nome do template<br><input class="regular-text" name="template_name" value="'.esc_attr($edit['template_name']??'Premium Certificate').'"></label></p><p><label>Título<br><input class="regular-text" name="certificate_title" value="'.esc_attr($edit['certificate_title']??'Certificate of Completion').'"></label></p>';
        echo '<p><label>Cor principal<br><input type="color" name="primary_color" value="'.esc_attr($edit['primary_color']??'#0f172a').'"></label></p><p><label>Cor destaque<br><input type="color" name="accent_color" value="'.esc_attr($edit['accent_color']??'#d9a441').'"></label></p><p><label>Fundo<br><input type="color" name="background_color" value="'.esc_attr($edit['background_color']??'#ffffff').'"></label></p><p><label>Estado<br><select name="status"><option value="active" '.selected(($edit['status']??'active'),'active',false).'>Ativo</option><option value="archived" '.selected(($edit['status']??''),'archived',false).'>Arquivado</option></select></label></p></div>';
        echo '<h3>Certificate Studio, tipografia e cores independentes</h3><div class="ffp-form-grid"><p><label>Títulos<br><input type="color" name="title_color" value="'.esc_attr($edit['title_color']??'#0f172a').'"></label></p><p><label>Subtítulos<br><input type="color" name="subtitle_color" value="'.esc_attr($edit['subtitle_color']??'#64748b').'"></label></p><p><label>Texto corpo<br><input type="color" name="body_color" value="'.esc_attr($edit['body_color']??'#334155').'"></label></p><p><label>Links<br><input type="color" name="link_color" value="'.esc_attr($edit['link_color']??'#2563eb').'"></label></p><p><label>Linhas e assinatura<br><input type="color" name="line_color" value="'.esc_attr($edit['line_color']??($edit['accent_color']??'#d9a441')).'"></label></p><p><label>Botões<br><input type="color" name="button_color" value="'.esc_attr($edit['button_color']??'#0f172a').'"></label></p><p><label>Texto dos botões<br><input type="color" name="button_text_color" value="'.esc_attr($edit['button_text_color']??'#ffffff').'"></label></p><p><label>Fundo modal<br><input type="color" name="modal_bg_color" value="'.esc_attr($edit['modal_bg_color']??'#ffffff').'"></label></p><p><label>Texto modal<br><input type="color" name="modal_text_color" value="'.esc_attr($edit['modal_text_color']??'#0f172a').'"></label></p><p><label>Fundo card badge<br><input type="color" name="card_bg_color" value="'.esc_attr($edit['card_bg_color']??'#ffffff').'"></label></p><p><label>Fonte títulos<br><input class="regular-text" name="title_font" list="ffp-fonts" value="'.esc_attr($edit['title_font']??'Helvetica-Bold').'" placeholder="Ex: Montserrat"></label></p><p><label>Fonte corpo<br><input class="regular-text" name="body_font" list="ffp-fonts" value="'.esc_attr($edit['body_font']??'Helvetica').'" placeholder="Ex: Inter"></label></p><datalist id="ffp-fonts"><option value="Helvetica-Bold"><option value="Helvetica"><option value="System UI"><option value="Inter"><option value="Arial"><option value="Verdana"><option value="Georgia"><option value="Times New Roman"><option value="Courier New"><option value="Poppins"><option value="Montserrat"><option value="Roboto"><option value="Lato"><option value="Open Sans"><option value="Playfair Display"></datalist><p class="ffp-small" style="grid-column:1/-1;margin-top:-8px">Podes escrever uma fonte instalada pelo tema/WordPress ou uma família CSS. No PDF, fontes externas podem usar fallback seguro.</p></div>';
        echo '<div class="ffp-form-grid"><p><label>Logo esquerdo URL<br><input class="regular-text" name="logo_left_url" value="'.esc_attr($edit['logo_left_url']??'').'" placeholder="https://..."></label></p><p><label>Logo direito URL<br><input class="regular-text" name="logo_right_url" value="'.esc_attr($edit['logo_right_url']??'').'" placeholder="https://..."></label></p><p><label>Selo da campanha/projeto URL<br><input class="regular-text" name="seal_image_url" value="'.esc_attr($edit['seal_image_url']??'').'" placeholder="PNG, JPG, WebP ou SVG da Media Library"></label><br><span class="ffp-small">Recomendado: PNG transparente 600x600. SVG funciona quando o servidor suporta Imagick.</span></p><p><label>Assinatura imagem URL<br><input class="regular-text" name="signature_url" value="'.esc_attr($edit['signature_url']??'').'" placeholder="https://..."></label></p><p><label>Nome signatário<br><input class="regular-text" name="signer_name" value="'.esc_attr($edit['signer_name']??'').'"></label></p><p><label>Cargo signatário<br><input class="regular-text" name="signer_role" value="'.esc_attr($edit['signer_role']??'').'"></label></p></div>';
        echo '<p><label>Texto do certificado<br><textarea name="certificate_text" rows="4" class="large-text">'.esc_textarea($edit['certificate_text']??'Certificamos que {{name}} concluiu com sucesso {{course}} no âmbito {{campaign}}.').'</textarea></label><br><span class="ffp-small">Variáveis disponíveis: {{name}}, {{course}}, {{campaign}}</span></p><p><button class="button button-primary">Guardar certificado</button></p></form></div>';
        $rows=$wpdb->get_results("SELECT * FROM {$settings_table} ORDER BY updated_at DESC,id DESC",ARRAY_A) ?: [];
        echo '<div class="ffp-card ffp-table"><h2>Templates de certificado</h2><table class="widefat striped"><thead><tr><th>ID</th><th>Template</th><th>Âmbito</th><th>Cores</th><th>Selo</th><th>Signatário</th><th>Ações</th></tr></thead><tbody>';
        foreach($rows as $r){ $edit_url=admin_url('admin.php?page=routespro-performance&tab=certificates&edit='.(int)$r['id']); echo '<tr><td>#'.esc_html($r['id']).'</td><td><strong>'.esc_html($r['template_name']).'</strong><br><span class="ffp-muted">'.esc_html($r['certificate_title']).'</span></td><td>Cliente '.esc_html((string)($r['client_id']?:'Global')).'<br>Campanha '.esc_html((string)($r['project_id']?:'Todas')).'</td><td><span style="display:inline-block;width:18px;height:18px;border-radius:99px;background:'.esc_attr($r['primary_color']).'"></span> <span style="display:inline-block;width:18px;height:18px;border-radius:99px;background:'.esc_attr($r['accent_color']).'"></span></td><td>'.(!empty($r['seal_image_url']) ? 'Personalizado' : 'Fallback FieldFlow').'</td><td>'.esc_html($r['signer_name'] ?: 'Sem signatário').'<br><span class="ffp-muted">'.esc_html($r['signer_role'] ?: '').'</span></td><td><a href="'.esc_url($edit_url).'">Editar</a></td></tr>'; }
        if(!$rows) echo '<tr><td colspan="7">Ainda sem templates guardados. O sistema usa um certificado global por defeito.</td></tr>'; echo '</tbody></table></div>';
        $certs=$wpdb->get_results("SELECT ce.*, u.display_name, c.title AS course_title FROM ".Module::table('certificates')." ce LEFT JOIN {$wpdb->users} u ON u.ID=ce.user_id LEFT JOIN ".Module::table('courses')." c ON c.id=ce.course_id ORDER BY ce.issued_at DESC LIMIT 30",ARRAY_A) ?: [];
        echo '<div class="ffp-card ffp-table"><h2>Últimos certificados emitidos</h2><table class="widefat striped"><thead><tr><th>ID</th><th>Utilizador</th><th>Curso</th><th>Emitido</th></tr></thead><tbody>';
        foreach($certs as $r){ echo '<tr><td>'.esc_html($r['certificate_uid']).'</td><td>'.esc_html($r['display_name']).'</td><td>'.esc_html($r['course_title']).'</td><td>'.esc_html($r['issued_at']).'</td></tr>'; }
        if(!$certs) echo '<tr><td colspan="4">Ainda sem certificados emitidos.</td></tr>'; echo '</tbody></table></div>';
    }


    private static function automations(): void {
        global $wpdb;
        $clients=Module::get_clients(); $projects=Module::get_projects(); $courses=Module::get_courses(); $forms=Module::get_forms();
        $edit_id=absint($_GET['edit'] ?? 0);
        $edit=$edit_id ? $wpdb->get_row($wpdb->prepare('SELECT * FROM '.Module::table('automations').' WHERE id=%d',$edit_id),ARRAY_A) : null;
        $rules=Module::get_automations(); $logs=Module::automation_logs(60);
        echo '<div class="ffp-card'.($edit?' ffp-editing':'').'"><h2>'.($edit?'Editar automação':'Nova automação').'</h2><p class="ffp-muted">Cria ações automáticas a partir das respostas dos reportes. Exemplo: se Material POS = Não, criar missão corretiva e atribuir formação.</p><form method="post" action="'.esc_url(admin_url('admin-post.php')).'">';
        wp_nonce_field('fieldflow_perf_save_automation');
        echo '<input type="hidden" name="action" value="fieldflow_perf_save_automation"><input type="hidden" name="automation_id" value="'.esc_attr((string)$edit_id).'">';
        echo '<div class="ffp-form-grid"><p><label>Nome da regra<br><input class="regular-text" name="name" value="'.esc_attr($edit['name'] ?? '').'" placeholder="POS não implementado"></label></p>';
        echo '<p><label>Cliente<br><select name="client_id"><option value="0">Todos</option>'; foreach($clients as $c) echo '<option value="'.esc_attr($c['id']).'" '.selected((int)($edit['client_id']??0),(int)$c['id'],false).'>'.esc_html($c['name']).'</option>'; echo '</select></label></p>';
        echo '<p><label>Campanha<br><select name="project_id"><option value="0">Todas</option>'; foreach($projects as $pr) echo '<option value="'.esc_attr($pr['id']).'" '.selected((int)($edit['project_id']??0),(int)$pr['id'],false).'>'.esc_html($pr['name']).'</option>'; echo '</select></label></p>';
        echo '<p><label>Formulário<br><select name="form_id"><option value="0">Todos</option>'; foreach($forms as $f) echo '<option value="'.esc_attr($f['id']).'" '.selected((int)($edit['form_id']??0),(int)$f['id'],false).'>'.esc_html($f['title']).'</option>'; echo '</select></label></p>';
        echo '<p><label>Estado<br><select name="status"><option value="active" '.selected(($edit['status']??'active'),'active',false).'>Ativa</option><option value="draft" '.selected(($edit['status']??''),'draft',false).'>Rascunho</option><option value="archived" '.selected(($edit['status']??''),'archived',false).'>Arquivada</option></select></label></p></div>';
        echo '<h3>Condição</h3><div class="ffp-form-grid"><p><label>Chave da pergunta<br><input name="question_key" class="regular-text" value="'.esc_attr($edit['question_key']??'').'" placeholder="material_pos"></label><br><span class="ffp-small">Usa a key técnica quando souberes.</span></p>';
        echo '<p><label>Ou texto exato da pergunta<br><input name="question_label" class="regular-text" value="'.esc_attr($edit['question_label']??'').'" placeholder="Material POS implementado?"></label></p>';
        echo '<p><label>Operador<br><select name="operator">'; $ops=['equals'=>'Igual a','not_equals'=>'Diferente de','contains'=>'Contém','not_contains'=>'Não contém','greater_than'=>'Maior que','less_than'=>'Menor que']; foreach($ops as $k=>$v) echo '<option value="'.esc_attr($k).'" '.selected(($edit['operator']??'equals'),$k,false).'>'.esc_html($v).'</option>'; echo '</select></label></p>';
        echo '<p><label>Valor<br><input name="compare_value" class="regular-text" value="'.esc_attr($edit['compare_value']??'').'" placeholder="Não"></label></p></div>';
        echo '<h3>Ações</h3><div class="ffp-form-grid"><p><label>Criar missão com título<br><input name="action_mission_title" class="regular-text" value="'.esc_attr($edit['action_mission_title']??'').'" placeholder="Corrigir implementação POS"></label></p>';
        echo '<p><label>Atribuir curso<br><select name="action_course_id"><option value="0">Nenhum</option>'; foreach($courses as $c) echo '<option value="'.esc_attr($c['id']).'" '.selected((int)($edit['action_course_id']??0),(int)$c['id'],false).'>'.esc_html($c['title']).'</option>'; echo '</select></label></p>';
        echo '<p><label>Pontos da missão<br><input type="number" name="action_points" value="'.esc_attr((string)($edit['action_points']??100)).'"></label></p>';
        echo '<p><label><input type="checkbox" name="action_email" value="1" '.checked(!empty($edit['action_email']),true,false).'> Enviar email ao operacional</label></p></div>';
        echo '<p><label>Descrição da missão<br><textarea name="action_mission_description" rows="3" class="large-text">'.esc_textarea($edit['action_mission_description']??'').'</textarea></label></p>';
        echo '<div class="ffp-form-grid"><p><label>Assunto email<br><input name="email_subject" class="regular-text" value="'.esc_attr($edit['email_subject']??'Nova ação FieldFlow').'" ></label></p><p><label>Corpo email<br><textarea name="email_body" rows="3" class="large-text">'.esc_textarea($edit['email_body']??'Olá {{name}}, foi criada uma nova ação no FieldFlow com base no teu reporte.').'</textarea></label><br><span class="ffp-small">Variáveis: {{name}}, {{answer}}, {{rule}}, {{submission_id}}</span></p></div>';
        echo '<p><button class="button button-primary">'.($edit?'Guardar automação':'Criar automação').'</button> '.($edit?'<a class="button" href="'.esc_url(admin_url('admin.php?page=routespro-performance&tab=automations')).'">Cancelar edição</a>':'').'</p></form></div>';
        echo '<div class="ffp-card ffp-table"><h2>Regras de automação</h2><table class="widefat striped"><thead><tr><th>ID</th><th>Regra</th><th>Âmbito</th><th>Condição</th><th>Ações</th><th>Estado</th><th></th></tr></thead><tbody>';
        foreach($rules as $r){ $edit_url=admin_url('admin.php?page=routespro-performance&tab=automations&edit='.(int)$r['id']); $del_url=wp_nonce_url(admin_url('admin-post.php?action=fieldflow_perf_delete_automation&id='.(int)$r['id']),'fieldflow_perf_delete_automation_'.(int)$r['id']); $actions=[]; if(!empty($r['action_mission_title']))$actions[]='Missão'; if(!empty($r['action_course_id']))$actions[]='Curso'; if(!empty($r['action_email']))$actions[]='Email'; echo '<tr><td>#'.esc_html($r['id']).'</td><td><strong>'.esc_html($r['name']).'</strong></td><td>Cliente '.esc_html((string)($r['client_id']?:'Todos')).'<br>Campanha '.esc_html((string)($r['project_id']?:'Todas')).'</td><td>'.esc_html(($r['question_key']?:$r['question_label']).' '.$r['operator'].' '.$r['compare_value']).'</td><td>'.esc_html($actions?implode(' + ',$actions):'Sem ações').'</td><td><span class="ffp-pill">'.esc_html($r['status']).'</span></td><td><span class="ffp-actions"><a href="'.esc_url($edit_url).'">Editar</a><a class="ffp-danger" href="'.esc_url($del_url).'" onclick="return confirm(\'Apagar esta automação?\')">Apagar</a></span></td></tr>'; }
        if(!$rules) echo '<tr><td colspan="7">Ainda sem automações.</td></tr>'; echo '</tbody></table></div>';
        echo '<div class="ffp-card ffp-table"><h2>Histórico de automações</h2><table class="widefat striped"><thead><tr><th>Data</th><th>Regra</th><th>Operacional</th><th>Submissão</th><th>Ações</th></tr></thead><tbody>';
        foreach($logs as $l){ $actions=json_decode((string)($l['actions_json']??'[]'),true); $txt=[]; if(is_array($actions)){ foreach($actions as $a){ $txt[]=$a['type'] ?? 'ação'; }} echo '<tr><td>'.esc_html($l['created_at']).'</td><td>'.esc_html($l['rule_name']).'</td><td>'.esc_html($l['display_name']).'</td><td>#'.esc_html((string)$l['submission_id']).'</td><td>'.esc_html($txt?implode(', ',$txt):'Sem ações registadas').'</td></tr>'; }
        if(!$logs) echo '<tr><td colspan="5">Ainda sem histórico.</td></tr>'; echo '</tbody></table></div>';
    }


    private static function reset_engine(): void {
        $clients = Module::get_clients();
        $projects = Module::get_projects();
        $courses = Module::get_courses(['include_inactive'=>1]);
        $client_id = absint($_GET['client_id'] ?? 0);
        $project_id = absint($_GET['project_id'] ?? 0);
        $course_id = absint($_GET['course_id'] ?? 0);
        $user_id = absint($_GET['user_id'] ?? 0);
        $rows = Module::get_reset_engine_rows($client_id, $project_id, $course_id, $user_id);
        echo '<div class="ffp-card"><h2>Reset Engine</h2><p class="ffp-muted">Reinicia o progresso de formação de um operacional sem mexer nos cursos, missões ou reportes. O reset remove progresso e certificado desse curso e regista histórico auditável.</p>';
        if (!empty($_GET['reset'])) echo '<div class="notice notice-success inline"><p>Progresso reiniciado com sucesso.</p></div>';
        echo '<form method="get" action="'.esc_url(admin_url('admin.php')).'"><input type="hidden" name="page" value="routespro-performance"><input type="hidden" name="tab" value="reset"><div class="ffp-form-grid">';
        echo '<p><label>Cliente<br><select name="client_id"><option value="0">Todos</option>'; foreach($clients as $c) echo '<option value="'.esc_attr($c['id']).'" '.selected($client_id,(int)$c['id'],false).'>'.esc_html($c['name']).'</option>'; echo '</select></label></p>';
        echo '<p><label>Campanha<br><select name="project_id"><option value="0">Todas</option>'; foreach($projects as $p) echo '<option value="'.esc_attr($p['id']).'" '.selected($project_id,(int)$p['id'],false).'>'.esc_html($p['name']).'</option>'; echo '</select></label></p>';
        echo '<p><label>Curso<br><select name="course_id"><option value="0">Todos</option>'; foreach($courses as $c) echo '<option value="'.esc_attr($c['id']).'" '.selected($course_id,(int)$c['id'],false).'>'.esc_html($c['title']).'</option>'; echo '</select></label></p>';
        echo '<p><label>User ID opcional<br><input type="number" name="user_id" value="'.esc_attr((string)$user_id).'" placeholder="Ex: 12"></label></p>';
        echo '<p style="align-self:end"><button class="button button-primary">Filtrar</button> <a class="button" href="'.esc_url(admin_url('admin.php?page=routespro-performance&tab=reset')).'">Limpar</a></p></div></form></div>';
        echo '<div class="ffp-card ffp-table"><h2>Progresso por operacional</h2><table class="widefat striped"><thead><tr><th>Operacional</th><th>Curso</th><th>Âmbito</th><th>Progresso</th><th>Certificado</th><th>Reset</th></tr></thead><tbody>';
        foreach($rows as $r){
            echo '<tr><td><strong>'.esc_html($r['display_name']).'</strong><br><span class="ffp-muted">'.esc_html($r['user_email']).'</span></td><td>'.esc_html($r['course_title']).'</td><td>Cliente #'.esc_html((string)$r['client_id']).'<br>Campanha #'.esc_html((string)$r['project_id']).'</td><td><strong>'.esc_html((string)$r['progress']).'%</strong><br><span class="ffp-muted">'.esc_html((string)$r['done']).' / '.esc_html((string)$r['required']).' lições obrigatórias</span></td><td>'.($r['certificate_uid'] ? esc_html($r['certificate_uid']).'<br><span class="ffp-muted">'.esc_html($r['issued_at']).'</span>' : '<span class="ffp-muted">Sem certificado</span>').'</td><td><form method="post" action="'.esc_url(admin_url('admin-post.php')).'" onsubmit="return confirm(\'Reiniciar progresso deste curso para este operacional?\')">';
            wp_nonce_field('fieldflow_perf_reset_course_progress');
            echo '<input type="hidden" name="action" value="fieldflow_perf_reset_course_progress"><input type="hidden" name="user_id" value="'.esc_attr((string)$r['user_id']).'"><input type="hidden" name="course_id" value="'.esc_attr((string)$r['course_id']).'"><textarea name="reason" rows="2" style="width:100%;min-width:220px" required placeholder="Motivo obrigatório"></textarea><br><button class="button button-secondary" style="margin-top:6px">Reiniciar curso</button></form></td></tr>';
        }
        if(!$rows) echo '<tr><td colspan="6">Sem operacionais encontrados. Conclui uma lição, emite certificado ou confirma associação do utilizador à campanha/cliente.</td></tr>';
        echo '</tbody></table></div>';
        $logs = Module::get_reset_logs(40);
        echo '<div class="ffp-card ffp-table"><h2>Histórico de resets</h2><table class="widefat striped"><thead><tr><th>Data</th><th>Operacional</th><th>Curso</th><th>Motivo</th><th>Admin</th></tr></thead><tbody>';
        foreach($logs as $l){ echo '<tr><td>'.esc_html($l['created_at']).'</td><td>'.esc_html($l['display_name'] ?: ('User #'.(int)$l['user_id'])).'</td><td>'.esc_html($l['course_title'] ?: ('Curso #'.(int)$l['course_id'])).'</td><td>'.esc_html($l['reason']).'</td><td>'.esc_html($l['admin_name'] ?: '').'</td></tr>'; }
        if(!$logs) echo '<tr><td colspan="5">Ainda sem resets registados.</td></tr>';
        echo '</tbody></table></div>';
    }


    private static function skills(): void {
        $skills = Module::get_skills(true);
        $courses = Module::get_courses(['include_inactive'=>1]);
        $missions = Module::get_missions();
        $object_type = sanitize_key($_GET['object_type'] ?? 'course');
        if (!in_array($object_type, ['course','mission'], true)) $object_type = 'course';
        $object_id = absint($_GET['object_id'] ?? 0);
        if (!$object_id && $object_type === 'course' && $courses) $object_id = (int)$courses[0]['id'];
        if (!$object_id && $object_type === 'mission' && $missions) $object_id = (int)$missions[0]['id'];
        $rules = $object_id ? Module::get_skill_rules($object_type, $object_id) : [];
        $rule_points = [];
        foreach ($rules as $r) $rule_points[(int)$r['skill_id']] = (int)$r['points'];
        echo '<div class="ffp-card"><h2>Skill Assignment</h2><p class="ffp-muted">Define que competências cada curso ou missão desenvolve. A Skill Matrix do Growth Hub passa a calcular valores reais com base na conclusão de cursos, certificados e missões aprovadas.</p>';
        if (!empty($_GET['saved'])) echo '<div class="notice notice-success inline"><p>Competência guardada.</p></div>';
        if (!empty($_GET['rules_saved'])) echo '<div class="notice notice-success inline"><p>Regras de competências guardadas.</p></div>';
        echo '<div class="ffp-form-grid"><form method="post" action="'.esc_url(admin_url('admin-post.php')).'" class="ffp-card" style="box-shadow:none">';
        wp_nonce_field('fieldflow_perf_save_skill');
        echo '<input type="hidden" name="action" value="fieldflow_perf_save_skill"><h3>Nova competência</h3><p><label>Nome<br><input class="regular-text" name="name" placeholder="Ex: Negociação" required></label></p><p><label>Descrição<br><textarea name="description" rows="3" class="large-text"></textarea></label></p><p><label>Cor<br><input type="color" name="color" value="#0f172a"></label></p><p><label>Ordem<br><input type="number" name="sort_order" value="10"></label></p><p><button class="button button-primary">Guardar competência</button></p></form>';
        echo '<div class="ffp-card" style="box-shadow:none"><h3>Competências existentes</h3><table class="widefat striped"><thead><tr><th>Nome</th><th>Cor</th><th>Estado</th></tr></thead><tbody>';
        foreach($skills as $s){ echo '<tr><td><strong>'.esc_html($s['name']).'</strong><br><span class="ffp-muted">'.esc_html($s['description'] ?? '').'</span></td><td><span style="display:inline-block;width:18px;height:18px;border-radius:99px;background:'.esc_attr($s['color']).'"></span> '.esc_html($s['color']).'</td><td>'.esc_html($s['status']).'</td></tr>'; }
        if(!$skills) echo '<tr><td colspan="3">Sem competências.</td></tr>';
        echo '</tbody></table></div></div></div>';
        echo '<div class="ffp-card"><h2>Atribuir competências a cursos e missões</h2><form method="get" action="'.esc_url(admin_url('admin.php')).'"><input type="hidden" name="page" value="routespro-performance"><input type="hidden" name="tab" value="skills"><div class="ffp-form-grid"><p><label>Tipo<br><select name="object_type" onchange="this.form.submit()"><option value="course" '.selected($object_type,'course',false).'>Curso</option><option value="mission" '.selected($object_type,'mission',false).'>Missão</option></select></label></p><p><label>Item<br><select name="object_id" onchange="this.form.submit()">';
        $items = $object_type === 'course' ? $courses : $missions;
        foreach($items as $it){ echo '<option value="'.esc_attr($it['id']).'" '.selected($object_id,(int)$it['id'],false).'>'.esc_html($it['title']).'</option>'; }
        echo '</select></label></p><p style="align-self:end"><button class="button">Carregar</button></p></div></form>';
        if(!$skills){ echo '<p class="ffp-muted">Cria primeiro pelo menos uma competência.</p>'; }
        elseif(!$object_id){ echo '<p class="ffp-muted">Ainda não existem cursos ou missões para atribuir competências.</p>'; }
        else {
            echo '<form method="post" action="'.esc_url(admin_url('admin-post.php')).'">';
            wp_nonce_field('fieldflow_perf_save_skill_rules');
            echo '<input type="hidden" name="action" value="fieldflow_perf_save_skill_rules"><input type="hidden" name="object_type" value="'.esc_attr($object_type).'"><input type="hidden" name="object_id" value="'.esc_attr((string)$object_id).'">';
            echo '<table class="widefat striped"><thead><tr><th>Competência</th><th>Pontos</th><th>Nota</th></tr></thead><tbody>';
            foreach($skills as $s){ if(($s['status'] ?? '') !== 'active') continue; $sid=(int)$s['id']; echo '<tr><td><strong>'.esc_html($s['name']).'</strong><br><span class="ffp-muted">'.esc_html($s['description'] ?? '').'</span></td><td><input type="number" min="0" max="100" name="skill_points['.esc_attr((string)$sid).']" value="'.esc_attr((string)($rule_points[$sid] ?? 0)).'" style="width:90px"></td><td><span class="ffp-muted">0 remove a atribuição. Recomendado: 5 a 40 pontos.</span></td></tr>'; }
            echo '</tbody></table><p><button class="button button-primary">Guardar atribuições</button></p></form>';
            if($rules){ echo '<h3>Regras atuais</h3><table class="widefat striped"><thead><tr><th>Competência</th><th>Pontos</th></tr></thead><tbody>'; foreach($rules as $r){ echo '<tr><td>'.esc_html($r['skill_name']).'</td><td>'.esc_html((string)$r['points']).'</td></tr>'; } echo '</tbody></table>'; }
        }
        echo '</div>';
    }


    private static function activity_feed_admin(): void {
        $clients = Module::get_clients();
        $projects = Module::get_projects();
        $client_id = absint($_GET['client_id'] ?? 0);
        $project_id = absint($_GET['project_id'] ?? 0);
        $user_id = absint($_GET['user_id'] ?? 0);
        $page_no = max(1, absint($_GET['feed_page'] ?? 1));
        $per_page = 12;
        $scoped_ids = $user_id ? [$user_id] : Module::scope_user_ids($client_id, $project_id);
        $activity = Module::activity_feed($client_id, $project_id, $user_id, '', '', $scoped_ids);
        $total = count($activity);
        $pages = max(1, (int)ceil($total / $per_page));
        if ($page_no > $pages) $page_no = $pages;
        $slice = array_slice($activity, ($page_no - 1) * $per_page, $per_page);
        echo '<div class="ffp-card"><h2>Activity Feed</h2><p class="ffp-muted">Gestão administrativa do histórico visível no Growth Hub. Limpar o feed apenas oculta eventos antigos neste âmbito, não apaga progresso, certificados, badges, cursos ou missões.</p>';
        if (!empty($_GET['ffp_activity_cleared'])) echo '<div class="notice notice-success inline"><p>Activity Feed limpo para o âmbito selecionado.</p></div>';
        echo '<form method="get" action="'.esc_url(admin_url('admin.php')).'"><input type="hidden" name="page" value="routespro-performance"><input type="hidden" name="tab" value="activity"><div class="ffp-form-grid">';
        echo '<p><label>Cliente<br><select name="client_id"><option value="0">Todos</option>'; foreach($clients as $c) echo '<option value="'.esc_attr($c['id']).'" '.selected($client_id,(int)$c['id'],false).'>'.esc_html($c['name']).'</option>'; echo '</select></label></p>';
        echo '<p><label>Campanha<br><select name="project_id"><option value="0">Todas</option>'; foreach($projects as $p) echo '<option value="'.esc_attr($p['id']).'" '.selected($project_id,(int)$p['id'],false).'>'.esc_html($p['name']).'</option>'; echo '</select></label></p>';
        echo '<p><label>User ID opcional<br><input type="number" name="user_id" value="'.esc_attr((string)$user_id).'" placeholder="Ex: 12"></label></p>';
        echo '<p style="align-self:end"><button class="button button-primary">Filtrar</button> <a class="button" href="'.esc_url(admin_url('admin.php?page=routespro-performance&tab=activity')).'">Limpar filtros</a></p></div></form>';
        echo '<form method="post" action="'.esc_url(admin_url('admin-post.php')).'" onsubmit="return confirm(\'Limpar a Activity Feed deste âmbito? Isto apenas oculta eventos antigos, não apaga progresso, certificados ou missões.\');" style="margin-top:10px">';
        wp_nonce_field('fieldflow_perf_clear_activity');
        echo '<input type="hidden" name="action" value="fieldflow_perf_clear_activity"><input type="hidden" name="client_id" value="'.esc_attr((string)$client_id).'"><input type="hidden" name="project_id" value="'.esc_attr((string)$project_id).'"><button class="button button-secondary">Limpar feed deste âmbito</button></form></div>';
        echo '<div class="ffp-card ffp-table"><h2>Eventos recentes</h2><p class="ffp-muted">A mostrar '.esc_html((string)count($slice)).' de '.esc_html((string)$total).' eventos.</p><table class="widefat striped"><thead><tr><th>Evento</th><th>Item</th><th>Utilizador</th><th>Data</th></tr></thead><tbody>';
        foreach($slice as $a){ echo '<tr><td><strong>'.esc_html($a['label']).'</strong></td><td>'.esc_html($a['item']).'</td><td>'.esc_html($a['display_name']).'</td><td>'.esc_html($a['date_label']).'</td></tr>'; }
        if(!$slice) echo '<tr><td colspan="4">Sem eventos neste âmbito.</td></tr>';
        echo '</tbody></table>';
        if($pages > 1){ echo '<p style="margin-top:14px">'; for($i=1;$i<=$pages;$i++){ $url=add_query_arg(['page'=>'routespro-performance','tab'=>'activity','client_id'=>$client_id,'project_id'=>$project_id,'user_id'=>$user_id,'feed_page'=>$i], admin_url('admin.php')); echo '<a class="button '.($i===$page_no?'button-primary':'').'" style="margin-right:4px" href="'.esc_url($url).'">'.esc_html((string)$i).'</a>'; } echo '</p>'; }
        echo '</div>';
    }

    private static function shortcodes(): void {
        echo '<div class="ffp-card"><h2>Shortcodes Growth Hub</h2><table class="widefat striped"><thead><tr><th>Shortcode</th><th>Função</th></tr></thead><tbody>';
        echo '<tr><td><code>[fieldflow_performance_dashboard]</code></td><td>Dashboard Growth Hub front para cliente ou campanha.</td></tr><tr><td><code>[fieldflow_academy]</code></td><td>Área de formação e missões para pessoas de terreno.</td></tr><tr><td><code>[fieldflow_client_portal]</code></td><td>Inclui a aba Growth Hub automaticamente.</td></tr><tr><td><code>[fieldflow_app]</code></td><td>Inclui a aba Academy automaticamente.</td></tr><tr><td><strong>Automações</strong></td><td>Regras que ligam respostas de reportes a missões, cursos e emails.</td></tr>';
        echo '</tbody></table></div>';
    }
}
