<?php
namespace RoutesPro\Admin;

use RoutesPro\Forms\ProductCardex as Cardex;

if (!defined('ABSPATH')) exit;

class ProductCardex {
    public static function register_hooks() {
        add_action('admin_post_routespro_save_product_cardex', [self::class, 'handle_save']);
        add_action('admin_post_routespro_delete_product_cardex', [self::class, 'handle_delete']);
        add_action('admin_post_routespro_import_product_cardex', [self::class, 'handle_import']);
        add_action('admin_post_routespro_product_cardex_template', [self::class, 'download_template']);
    }
    private static function locations(): array { global $wpdb; return $wpdb->get_results("SELECT id,name,external_ref,client_id,project_id FROM {$wpdb->prefix}routespro_locations ORDER BY name ASC LIMIT 3000", ARRAY_A) ?: []; }
    private static function linked_locations(int $cardex_id): array { global $wpdb; Cardex::install(); $ids=$wpdb->get_col($wpdb->prepare("SELECT location_id FROM ".Cardex::table_locations()." WHERE cardex_id=%d", $cardex_id)); return array_map('intval',$ids ?: []); }
    public static function render() {
        if (!current_user_can('routespro_manage')) wp_die('Sem permissões.'); Cardex::install();
        $edit_id = absint($_GET['edit'] ?? 0); $edit = $edit_id ? Cardex::get_cardex($edit_id) : null; $items = $edit_id ? Cardex::get_items($edit_id) : [];
        $linked = $edit_id ? self::linked_locations($edit_id) : [];
        echo '<div class="wrap">'; Branding::render_header('Cardex de Produtos', 'Cria listas de referências por insígnia ou tipo de loja e usa-as nas perguntas de tabela de produtos.');
        if(isset($_GET['saved'])) echo '<div class="notice notice-success"><p>Cardex guardado.</p></div>'; if(isset($_GET['imported'])) echo '<div class="notice notice-success"><p>CSV importado.</p></div>';
        echo '<div style="display:grid;grid-template-columns:minmax(320px,520px) 1fr;gap:18px;align-items:start">';
        echo '<div class="routespro-card" style="background:#fff;border:1px solid #dcdcde;border-radius:14px;padding:16px"><h2>'.($edit?'Editar cardex':'Novo cardex').'</h2>';
        echo '<form method="post" action="'.esc_url(admin_url('admin-post.php')).'"><input type="hidden" name="action" value="routespro_save_product_cardex"><input type="hidden" name="id" value="'.(int)$edit_id.'">'; wp_nonce_field('routespro_save_product_cardex','routespro_product_cardex_nonce');
        echo '<p><label><strong>Nome</strong><br><input type="text" name="name" class="regular-text" value="'.esc_attr($edit['name'] ?? '').'" placeholder="Ex, Sonae" required></label></p>';
        echo '<p><label><strong>Insígnia / palavra-chave</strong><br><input type="text" name="insignia" class="regular-text" value="'.esc_attr($edit['insignia'] ?? '').'" placeholder="Ex, Continente, Pingo Doce"></label><br><span class="description">Usado para auto-detetar quando a loja não está associada manualmente.</span></p>';
        echo '<p><label>Cliente ID <input type="number" name="client_id" value="'.esc_attr((string)($edit['client_id'] ?? 0)).'" style="width:90px"></label> <label>Projeto ID <input type="number" name="project_id" value="'.esc_attr((string)($edit['project_id'] ?? 0)).'" style="width:90px"></label></p>';
        echo '<p><label><strong>Produtos</strong><br><textarea name="products_text" rows="10" style="width:100%;font-family:ui-monospace,monospace" placeholder="referencia;produto">'.esc_textarea(implode("\n", array_map(function($r){return (($r['ref']??'').';'.($r['name']??''));}, $items))).'</textarea></label><br><span class="description">Formato: <code>referencia;produto</code>. A referência pode ficar vazia.</span></p>';
        $locs = self::locations(); echo '<p><strong>Associar a lojas existentes</strong><br><select name="location_ids[]" multiple size="8" style="width:100%;max-width:100%">';
        foreach($locs as $l){ $sel=in_array((int)$l['id'],$linked,true)?' selected':''; echo '<option value="'.(int)$l['id'].'"'.$sel.'>#'.(int)$l['id'].' · '.esc_html($l['name']).(!empty($l['external_ref'])?' · '.esc_html($l['external_ref']):'').'</option>'; }
        echo '</select><br><span class="description">Podes usar Ctrl/Cmd para selecionar várias lojas. O cardex escolhido aqui manda sobre a deteção automática.</span></p>';
        submit_button($edit?'Guardar cardex':'Criar cardex'); echo '</form>';
        echo '<hr><h3>Importar CSV</h3><form method="post" enctype="multipart/form-data" action="'.esc_url(admin_url('admin-post.php')).'"><input type="hidden" name="action" value="routespro_import_product_cardex">'; wp_nonce_field('routespro_import_product_cardex','routespro_product_cardex_import_nonce');
        echo '<p><input type="file" name="cardex_csv" accept=".csv,text/csv" required></p><p><label><input type="checkbox" name="replace_items" value="1" checked> Substituir produtos dos cardex importados</label></p><p><button class="button button-primary">Importar CSV</button> <a class="button" href="'.esc_url(admin_url('admin-post.php?action=routespro_product_cardex_template')).'">Template CSV</a></p><p class="description">CSV: cardex,insignia,client_id,project_id,referencia,produto,location_id,external_ref,ordem,ativo.</p></form>';
        echo '</div><div><h2>Cardex existentes</h2><table class="widefat striped"><thead><tr><th>ID</th><th>Nome</th><th>Insígnia</th><th>Produtos</th><th>Ações</th></tr></thead><tbody>';
        $rows=Cardex::list_cardex(); if(!$rows) echo '<tr><td colspan="5">Ainda não existem cardex.</td></tr>'; foreach($rows as $r){ global $wpdb; $cnt=(int)$wpdb->get_var($wpdb->prepare("SELECT COUNT(*) FROM ".Cardex::table_items()." WHERE cardex_id=%d AND is_active=1", (int)$r['id'])); $editurl=admin_url('admin.php?page=routespro-product-cardex&edit='.(int)$r['id']); $del=wp_nonce_url(admin_url('admin-post.php?action=routespro_delete_product_cardex&id='.(int)$r['id']),'routespro_delete_product_cardex_'.(int)$r['id']); echo '<tr><td>'.(int)$r['id'].'</td><td><strong>'.esc_html($r['name']).'</strong></td><td>'.esc_html($r['insignia']).'</td><td>'.$cnt.'</td><td><a class="button button-small" href="'.esc_url($editurl).'">Editar</a> <a class="button button-small" href="'.esc_url($del).'" onclick="return confirm(\'Apagar cardex?\')">Apagar</a></td></tr>'; }
        echo '</tbody></table></div></div></div>';
    }
    public static function handle_save(){ if(!current_user_can('routespro_manage')) wp_die('Sem permissões.'); check_admin_referer('routespro_save_product_cardex','routespro_product_cardex_nonce'); Cardex::install(); global $wpdb; $id=absint($_POST['id']??0); $data=['name'=>sanitize_text_field(wp_unslash($_POST['name']??'')) ?: 'Cardex','insignia'=>sanitize_text_field(wp_unslash($_POST['insignia']??'')),'client_id'=>absint($_POST['client_id']??0),'project_id'=>absint($_POST['project_id']??0),'status'=>'active','updated_at'=>current_time('mysql')]; if($id){$wpdb->update(Cardex::table_cardex(),$data,['id'=>$id]);}else{$data['created_at']=current_time('mysql');$wpdb->insert(Cardex::table_cardex(),$data);$id=(int)$wpdb->insert_id;} self::replace_items($id,(string)wp_unslash($_POST['products_text']??'')); self::replace_locations($id,array_map('absint',(array)($_POST['location_ids']??[]))); wp_safe_redirect(admin_url('admin.php?page=routespro-product-cardex&edit='.$id.'&saved=1')); exit; }
    private static function replace_items(int $id,string $text): void { global $wpdb; $wpdb->delete(Cardex::table_items(),['cardex_id'=>$id],['%d']); $lines=preg_split('/\r\n|\r|\n/',$text); $i=0; foreach($lines as $line){ $line=trim($line); if($line==='') continue; $parts=str_getcsv($line,';'); if(count($parts)<2) $parts=str_getcsv($line,','); $ref=sanitize_text_field($parts[0]??''); $name=sanitize_text_field($parts[1]??''); if($name==='' && $ref!==''){ $name=$ref; $ref=''; } if($name==='') continue; $wpdb->insert(Cardex::table_items(),['cardex_id'=>$id,'reference'=>$ref,'product_name'=>$name,'sort_order'=>$i++,'is_active'=>1,'created_at'=>current_time('mysql'),'updated_at'=>current_time('mysql')]); } }
    private static function replace_locations(int $id,array $locs): void { global $wpdb; $wpdb->delete(Cardex::table_locations(),['cardex_id'=>$id],['%d']); foreach(array_unique(array_filter($locs)) as $loc){ $wpdb->insert(Cardex::table_locations(),['cardex_id'=>$id,'location_id'=>(int)$loc,'created_at'=>current_time('mysql')]); } }
    public static function handle_delete(){ if(!current_user_can('routespro_manage')) wp_die('Sem permissões.'); $id=absint($_GET['id']??0); check_admin_referer('routespro_delete_product_cardex_'.$id); global $wpdb; Cardex::install(); $wpdb->delete(Cardex::table_items(),['cardex_id'=>$id]); $wpdb->delete(Cardex::table_locations(),['cardex_id'=>$id]); $wpdb->delete(Cardex::table_cardex(),['id'=>$id]); wp_safe_redirect(admin_url('admin.php?page=routespro-product-cardex')); exit; }
    public static function download_template(){ if(!current_user_can('routespro_manage')) wp_die('Sem permissões.'); nocache_headers(); header('Content-Type:text/csv; charset=utf-8'); header('Content-Disposition: attachment; filename="fieldflow-cardex-template.csv"'); $out=fopen('php://output','w'); fputcsv($out,['cardex','insignia','client_id','project_id','referencia','produto','location_id','external_ref','ordem','ativo']); fputcsv($out,['Sonae','Continente','0','0','JAM001','Jameson','','','1','1']); fputcsv($out,['Sonae','Continente','0','0','','Produto sem referência','','','2','1']); fclose($out); exit; }
    public static function handle_import(){ if(!current_user_can('routespro_manage')) wp_die('Sem permissões.'); check_admin_referer('routespro_import_product_cardex','routespro_product_cardex_import_nonce'); Cardex::install(); if(empty($_FILES['cardex_csv']['tmp_name'])) wp_die('CSV em falta.'); $replace=!empty($_POST['replace_items']); $fh=fopen($_FILES['cardex_csv']['tmp_name'],'r'); if(!$fh) wp_die('Não foi possível ler o CSV.'); $first=fgets($fh); if($first===false) wp_die('CSV sem cabeçalho.'); $delimiter=(substr_count($first,';')>substr_count($first,','))?';':','; $headers=str_getcsv($first,$delimiter); if(!$headers) wp_die('CSV sem cabeçalho.'); $headers=array_map(function($h){return strtolower(trim((string)$h));},$headers); global $wpdb; $seen=[]; while(($row=fgetcsv($fh,0,$delimiter))!==false){ $r=[]; foreach($headers as $i=>$h){$r[$h]=$row[$i]??'';} $name=sanitize_text_field($r['cardex']??$r['insignia']??''); if($name==='') continue; $ins=sanitize_text_field($r['insignia']??$name); $client=absint($r['client_id']??0); $project=absint($r['project_id']??0); $cid=(int)$wpdb->get_var($wpdb->prepare("SELECT id FROM ".Cardex::table_cardex()." WHERE name=%s AND client_id=%d AND project_id=%d LIMIT 1",$name,$client,$project)); if(!$cid){$wpdb->insert(Cardex::table_cardex(),['name'=>$name,'insignia'=>$ins,'client_id'=>$client,'project_id'=>$project,'status'=>'active','created_at'=>current_time('mysql'),'updated_at'=>current_time('mysql')]);$cid=(int)$wpdb->insert_id;} elseif($replace && empty($seen[$cid])){ $wpdb->delete(Cardex::table_items(),['cardex_id'=>$cid]); $seen[$cid]=true; }
            $prod=sanitize_text_field($r['produto']??$r['product']??''); if($prod!==''){ $wpdb->insert(Cardex::table_items(),['cardex_id'=>$cid,'reference'=>sanitize_text_field($r['referencia']??$r['reference']??''),'product_name'=>$prod,'sort_order'=>absint($r['ordem']??$r['order']??0),'is_active'=>isset($r['ativo'])?(int)!empty($r['ativo']):1,'created_at'=>current_time('mysql'),'updated_at'=>current_time('mysql')]); }
            $loc=absint($r['location_id']??0); if(!$loc && !empty($r['external_ref'])) $loc=(int)$wpdb->get_var($wpdb->prepare("SELECT id FROM {$wpdb->prefix}routespro_locations WHERE external_ref=%s LIMIT 1", sanitize_text_field($r['external_ref']))); if($loc){ $wpdb->replace(Cardex::table_locations(),['cardex_id'=>$cid,'location_id'=>$loc,'created_at'=>current_time('mysql')]); }
        } fclose($fh); wp_safe_redirect(admin_url('admin.php?page=routespro-product-cardex&imported=1')); exit; }
}
